INSERT INTO [dbo].[Categories] (Name) 
VALUES
('General Knowledge'),
('Entertainment: Books'),
('Entertainment: Film'),
('Entertainment: Music'),
('Entertainment: Musicals & Theatres'),
('Entertainment: Television'),
('Entertainment: Video Games'),
('Entertainment: Board Games'),
('Science & Nature'),
('Science: Computers'),
('Science: Mathematics'),
('Mythology'),
('Sports'),
('Geography'),
('History'),
('Politics'),
('Art'),
('Animals'),
('Vehicles'),
('Entertainment: Comics'),
('Science: Gadgets'),
('Entertainment: Japanese Anime & Manga'),
('Entertainment: Cartoon & Animations');
